// di/types.ts
export const TYPES = {
  IAdminController: Symbol.for("IAdminController"),
  IAdminService: Symbol.for("IAdminService"),
  IAdminRepository: Symbol.for("IAdminRepository"),
  IAuthController: Symbol.for("IAuthController"),
  IAuthService: Symbol.for("IAuthService"),
  IAuthRepository: Symbol.for("IAuthRepository"),
  ITokenRepository: Symbol.for("ITokenRepository"),
  ITempUserRepository: Symbol.for("ITempUserRepository"),
  IResetTokenRepository: Symbol.for("IResetTokenRepository"),
  IUserController: Symbol.for("IUserController"),
  IUserService: Symbol.for("IUserService"),
  IUserRepository: Symbol.for("IUserRepository"),
  IVehicleController: Symbol.for("IVehicleController"),
  IVehicleService: Symbol.for("IVehicleService"),
  IVehicleRepository: Symbol.for("IVehicleRepository"),
  IRideController: Symbol.for("IRideController"),
  IRideService: Symbol.for("IRideService"),
  IRideRepository: Symbol.for("IRideRepository"),
  ISubscriptionController: Symbol.for("ISubscriptionController"),
  ISubscriptionService: Symbol.for("ISubscriptionService"),
  ISubscriptionRepository: Symbol.for("ISubscriptionRepository"),
  IWalletController: Symbol.for("IWalletController"),
  IWalletService: Symbol.for("IWalletService"),
  IWalletRepository: Symbol.for("IWalletRepository"),
  IOSRMClient: Symbol.for("IOSRMClient"),
};